### PR TITLE
Add user95401.gdPlatformerMode@1

### PR DESCRIPTION
**Pull request by user95401**
https://github.com/user95401/gdPlatformerMode/releases/download/3.0.0.0/user95401.gdPlatformerMode.geode

### CODE REVIEW

**Comment by matcool** [comment]
> This is traditional mod that uses minhook!
No!

**Comment by user95401** [comment]
oh, it needs more explanation

**Comment by user95401** [comment]
why no?
> BUT! In general, this mod works, and IN MOST CASES IT is COMPATIBLE.

**Comment by altalk23** [comment]
we are never accepting a traditional mod. period.

**Comment by user95401** [comment]
:(

**Comment by user95401** [comment]
Ok im back.
Pls give a chance.
Its good thing.
I want see it in index, I think it's decent.
😗🙏

**Comment by FigmentBoy** [comment]
I may be crazy but your source code still uses Minhook so I'm inclined to think you just packaged a Minhook mod into a geode file.

**Comment by user95401** [comment]
https://github.com/user95401/gdPlatformerMode/blob/main/geode/

Its literaly a tradicional gd.h + cocos-haders + minhook mod that packed for geode

**Comment by user95401** [comment]
And that works for geode or other dlls.
Like, I install about 10 geode mods and all of them works stable.
Even multiplayer one

**Comment by FigmentBoy** [comment]
The whole point of Geode is to use the hooking system. Every mod on the index uses Geode hooks.

**Comment by Alphatism** [comment]
Traditional mods can and will have issues, port the mod to geode, it really isn’t that hard.

**Comment by spinningtoilet0** [comment]
> we are never accepting a traditional mod. period.

Introducing a hooking framework other than Geode's is a hard rejection from the index. If you want your mod to be added, please adhere to the rules [here](https://docs.geode-sdk.org/source/indexrules).

**Comment by user95401** [comment]
I read rules.
My mod is not contain malware.
My mod is not 100% resulting incompatibility
My mod is not introduces severe security
And does not features explicit content
What problem

**Comment by FigmentBoy** [comment]
image

**Comment by user95401** [comment]
Minhook on geode not that fair if use it with ingenuity

**Comment by user95401** [comment]
And sub point is important?

**Comment by FigmentBoy** [comment]
I'm going to lock this thread now. There is no reason for you to keep trying to convince us to add a mod that doesn't adhere to our guidelines. If you remake it with without Minhook and with Geode, we can consider adding it.

**Pull request closed without merging**
